/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uabc.labs.pf.algoritmos;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author ACR
 */
public class GraficaUI extends javax.swing.JFrame {
Numeros numeros;
JTextField[] nodos;
    /**
     * Creates new form GraficaUI
     */
    public GraficaUI() {
        initComponents();
        scalaImagen(lineaD12);
        scalaImagen(lineaI12);
        scalaImagen(lineaD13);
        scalaImagen(lineaI13);
        scalaImagen(lineaD14);
        scalaImagen(lineaI14);
        scalaImagen(fondo);
        scalaImagen(fondoPrincipal);
        numeros = new Numeros();
        nodos = new JTextField[]{nodo1_1,nodo2_1,nodo2_2,nodo3_1,nodo3_2,nodo3_3,nodo3_4,
            nodo4_1,nodo4_2,nodo4_3,nodo4_4,nodo4_5,nodo4_6,nodo4_7,nodo4_8,nodo5_1,nodo5_2,
            nodo5_3,nodo5_4,nodo5_5,nodo5_6,nodo5_7,nodo5_8,nodo5_9,nodo5_10,nodo5_11,nodo5_12
            ,nodo5_13,nodo5_14,nodo5_15,nodo5_16};
    }

    
     /**
     * metodo para escalar la imagen al tamano del label
     * @param label 
     */
    public static void scalaImagen(javax.swing.JLabel label)
    {
        if(label.getIcon()==null) return; //no hacer nada si no hay imagen
        javax.swing.Icon i = label.getIcon();
        ImageIcon icon = (ImageIcon) i;
        java.awt.Image image = icon.getImage().getScaledInstance(label.getWidth(), 
             label.getHeight(), java.awt.Image.SCALE_SMOOTH);
        label.setIcon(new javax.swing.ImageIcon(image));
    }
    
    public void asignarPosiciones()
    {
      //ayuda!  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenedorArbol = new javax.swing.JPanel();
        nivel5 = new javax.swing.JPanel();
        nodo5_1 = new javax.swing.JTextField();
        nodo5_2 = new javax.swing.JTextField();
        nodo5_3 = new javax.swing.JTextField();
        nodo5_4 = new javax.swing.JTextField();
        nodo5_5 = new javax.swing.JTextField();
        nodo5_6 = new javax.swing.JTextField();
        nodo5_7 = new javax.swing.JTextField();
        nodo5_8 = new javax.swing.JTextField();
        nodo5_9 = new javax.swing.JTextField();
        nodo5_10 = new javax.swing.JTextField();
        nodo5_11 = new javax.swing.JTextField();
        nodo5_12 = new javax.swing.JTextField();
        nodo5_13 = new javax.swing.JTextField();
        nodo5_14 = new javax.swing.JTextField();
        nodo5_15 = new javax.swing.JTextField();
        nodo5_16 = new javax.swing.JTextField();
        lineaD = new javax.swing.JLabel();
        lineaI = new javax.swing.JLabel();
        lineaD1 = new javax.swing.JLabel();
        lineaI1 = new javax.swing.JLabel();
        lineaI2 = new javax.swing.JLabel();
        lineaD2 = new javax.swing.JLabel();
        lineaI3 = new javax.swing.JLabel();
        lineaD3 = new javax.swing.JLabel();
        lineaI4 = new javax.swing.JLabel();
        lineaD4 = new javax.swing.JLabel();
        lineaI5 = new javax.swing.JLabel();
        lineaD5 = new javax.swing.JLabel();
        lineaD6 = new javax.swing.JLabel();
        lineaI6 = new javax.swing.JLabel();
        lineaI7 = new javax.swing.JLabel();
        lineaD7 = new javax.swing.JLabel();
        lineaI8 = new javax.swing.JLabel();
        lineaD8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nodo4_1 = new javax.swing.JTextField();
        nodo4_2 = new javax.swing.JTextField();
        nodo4_3 = new javax.swing.JTextField();
        nodo4_4 = new javax.swing.JTextField();
        nodo4_5 = new javax.swing.JTextField();
        nodo4_6 = new javax.swing.JTextField();
        nodo4_7 = new javax.swing.JTextField();
        nodo4_8 = new javax.swing.JTextField();
        lineaI9 = new javax.swing.JLabel();
        lineaD9 = new javax.swing.JLabel();
        lineaD10 = new javax.swing.JLabel();
        lineaI10 = new javax.swing.JLabel();
        lineaD11 = new javax.swing.JLabel();
        lineaI11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nodo3_1 = new javax.swing.JTextField();
        nodo3_2 = new javax.swing.JTextField();
        nodo3_3 = new javax.swing.JTextField();
        nodo3_4 = new javax.swing.JTextField();
        lineaI13 = new javax.swing.JLabel();
        lineaD13 = new javax.swing.JLabel();
        lineaD12 = new javax.swing.JLabel();
        lineaI12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nodo2_1 = new javax.swing.JTextField();
        nodo2_2 = new javax.swing.JTextField();
        nodo1_1 = new javax.swing.JTextField();
        lineaD14 = new javax.swing.JLabel();
        lineaI14 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        generaB = new javax.swing.JButton();
        numValoresCB = new javax.swing.JComboBox<>();
        numValoresTexto = new javax.swing.JLabel();
        rango = new javax.swing.JTextField();
        rangoTexto = new javax.swing.JLabel();
        InsertaB = new javax.swing.JButton();
        inserta = new javax.swing.JTextField();
        eliminaB = new javax.swing.JButton();
        elimina = new javax.swing.JTextField();
        ordenes = new javax.swing.JLabel();
        mostrarOrdenadoTexto = new javax.swing.JLabel();
        preordenB = new javax.swing.JButton();
        inordenB = new javax.swing.JButton();
        postordenB = new javax.swing.JButton();
        RecPorNivB = new javax.swing.JButton();
        mostrarValNivB = new javax.swing.JButton();
        nivelCB = new javax.swing.JComboBox<>();
        codigoB = new javax.swing.JButton();
        codigo = new javax.swing.JTextField();
        fondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titulo.setText("  Oh! Un Arbol Binario!");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 195, -1));

        descripcion.setText("Crea tu propio arbol Binario de numeros!");
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 6, 248, 22));

        contenedorArbol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nivel5.setOpaque(false);

        nodo5_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        nodo5_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        nodo5_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        nodo5_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        nodo5_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        nodo5_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        nodo5_13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        nodo5_15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));

        nodo5_16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo5_16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo5_16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));

        javax.swing.GroupLayout nivel5Layout = new javax.swing.GroupLayout(nivel5);
        nivel5.setLayout(nivel5Layout);
        nivel5Layout.setHorizontalGroup(
            nivel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nivel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nodo5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nodo5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nodo5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nodo5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nodo5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nodo5_11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nodo5_13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nodo5_15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(nodo5_16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        nivel5Layout.setVerticalGroup(
            nivel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nivel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nivel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nivel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nodo5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nivel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nodo5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nodo5_16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        contenedorArbol.add(nivel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1430, 30));

        lineaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        lineaI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lineaD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        lineaI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        lineaI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        lineaD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        lineaI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        lineaD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        lineaI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));

        lineaD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, -1, -1));

        lineaI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, -1, -1));

        lineaD5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, -1, -1));

        lineaD6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 340, -1, -1));

        lineaI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 340, -1, -1));

        lineaI7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq4a5.png"))); // NOI18N
        contenedorArbol.add(lineaI7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 340, -1, -1));

        lineaD7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer4a5.png"))); // NOI18N
        contenedorArbol.add(lineaD7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 340, -1, -1));

        lineaI8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq3a4.png"))); // NOI18N
        contenedorArbol.add(lineaI8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 250, -1, -1));

        lineaD8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDe3a4r.png"))); // NOI18N
        contenedorArbol.add(lineaD8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, -1, -1));

        jPanel1.setOpaque(false);

        nodo4_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo4_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo4_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo4_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo4_5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo4_6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo4_7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo4_8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo4_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo4_8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nodo4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(nodo4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(nodo4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(nodo4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(nodo4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(nodo4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(nodo4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(nodo4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodo4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo4_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo4_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        contenedorArbol.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 1380, 30));

        lineaI9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq3a4.png"))); // NOI18N
        contenedorArbol.add(lineaI9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        lineaD9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDe3a4r.png"))); // NOI18N
        contenedorArbol.add(lineaD9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 250, -1, -1));

        lineaD10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDe3a4r.png"))); // NOI18N
        contenedorArbol.add(lineaD10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        lineaI10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq3a4.png"))); // NOI18N
        contenedorArbol.add(lineaI10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        lineaD11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDe3a4r.png"))); // NOI18N
        contenedorArbol.add(lineaD11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        lineaI11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq3a4.png"))); // NOI18N
        contenedorArbol.add(lineaI11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jPanel2.setOpaque(false);

        nodo3_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo3_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo3_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo3_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo3_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo3_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo3_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo3_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo3_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(nodo3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312)
                .addComponent(nodo3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304)
                .addComponent(nodo3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addComponent(nodo3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodo3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedorArbol.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1400, 30));

        lineaI13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq2a3.png"))); // NOI18N
        lineaI13.setText("jLabel1");
        contenedorArbol.add(lineaI13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 150, 70));

        lineaD13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer2a3.png"))); // NOI18N
        lineaD13.setText("jLabel1");
        contenedorArbol.add(lineaD13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 150, 140, 70));

        lineaD12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer2a3.png"))); // NOI18N
        contenedorArbol.add(lineaD12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 160, 70));

        lineaI12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq2a3.png"))); // NOI18N
        lineaI12.setText("jLabel1");
        contenedorArbol.add(lineaI12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, 70));

        jPanel3.setOpaque(false);

        nodo2_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo2_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        nodo2_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo2_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(nodo2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 660, Short.MAX_VALUE)
                .addComponent(nodo2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodo2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodo2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        contenedorArbol.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1400, 30));

        nodo1_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nodo1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nodo1_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 102)));
        contenedorArbol.add(nodo1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 50, -1));

        lineaD14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagDer1a2.png"))); // NOI18N
        lineaD14.setText("jLabel1");
        contenedorArbol.add(lineaD14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 310, 40));

        lineaI14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagIzq1a2.png"))); // NOI18N
        contenedorArbol.add(lineaI14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 330, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoArbol.jpg"))); // NOI18N
        contenedorArbol.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 410));

        jScrollPane1.setViewportView(contenedorArbol);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 534, 331));

        generaB.setText("Genera Valores");
        generaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaBActionPerformed(evt);
            }
        });
        getContentPane().add(generaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 14, -1, -1));

        numValoresCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(numValoresCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 47, -1, -1));

        numValoresTexto.setText("Num. Valores");
        getContentPane().add(numValoresTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 52, -1, -1));
        getContentPane().add(rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 79, 75, -1));

        rangoTexto.setText("Rango 0-?");
        getContentPane().add(rangoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 84, -1, -1));

        InsertaB.setText("Inserta num.");
        InsertaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertaBActionPerformed(evt);
            }
        });
        getContentPane().add(InsertaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 111, 101, -1));
        getContentPane().add(inserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 111, 60, -1));

        eliminaB.setText("Elimina num.");
        getContentPane().add(eliminaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 150, -1, -1));
        getContentPane().add(elimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 150, 60, -1));

        ordenes.setText("Secuencia A Mostrar: ");
        getContentPane().add(ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 695, 36));

        mostrarOrdenadoTexto.setText("Seccion De Mostra Ordenado!");
        getContentPane().add(mostrarOrdenadoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 195, -1, -1));

        preordenB.setText("Mostrar Preorden");
        preordenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preordenBActionPerformed(evt);
            }
        });
        getContentPane().add(preordenB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        inordenB.setText("Mostrar Inorden");
        inordenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inordenBActionPerformed(evt);
            }
        });
        getContentPane().add(inordenB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 130, -1));

        postordenB.setText("Mostrar Postorden");
        postordenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postordenBActionPerformed(evt);
            }
        });
        getContentPane().add(postordenB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 150, -1));

        RecPorNivB.setText("Mostrar RecorridoPorNivel");
        RecPorNivB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecPorNivBActionPerformed(evt);
            }
        });
        getContentPane().add(RecPorNivB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        mostrarValNivB.setText("Mostrar Valores En Nivel:");
        mostrarValNivB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarValNivBActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarValNivB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        nivelCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(nivelCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        codigoB.setText("Mostrar Codigo");
        codigoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBActionPerformed(evt);
            }
        });
        getContentPane().add(codigoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 130, -1));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 50, -1));

        fondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoAzul.jpg"))); // NOI18N
        fondoPrincipal.setText("jLabel2");
        getContentPane().add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaBActionPerformed
       ArrayList<Integer> nums = numeros.generaNumeros(10, 20);
       numeros.insertaNumeros(nums);
    }//GEN-LAST:event_generaBActionPerformed

    private void InsertaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertaBActionPerformed

    private void mostrarValNivBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarValNivBActionPerformed
      if(numeros.getArbol1().getRaiz()!=null)
      {
        int val = Integer.parseInt(nivelCB.getSelectedItem().toString());
        String cadena = numeros.getArbol1().mostrarPorNivel(val);
       ordenes.setText("Secuencia A Mostrar: "+cadena);
      }
    }//GEN-LAST:event_mostrarValNivBActionPerformed

    private void preordenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preordenBActionPerformed
       if(numeros.getArbol1().getRaiz()!=null)
      {
        String cadena = numeros.getArbol1().preorden();
       ordenes.setText("Secuencia A Mostrar: "+cadena);
      }
    }//GEN-LAST:event_preordenBActionPerformed

    private void inordenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inordenBActionPerformed
       if(numeros.getArbol1().getRaiz()!=null)
      {
        String cadena = numeros.getArbol1().inorden();
       ordenes.setText("Secuencia A Mostrar: "+cadena);
      }
    }//GEN-LAST:event_inordenBActionPerformed

    private void postordenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postordenBActionPerformed
       if(numeros.getArbol1().getRaiz()!=null)
      {
       String cadena = numeros.getArbol1().postorden();
       ordenes.setText("Secuencia A Mostrar: "+cadena);
      }
    }//GEN-LAST:event_postordenBActionPerformed

    private void codigoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBActionPerformed
      if(numeros.getArbol1().getRaiz()!=null && !codigo.getText().isEmpty())
      {
       String cadena;
       cadena = numeros.getArbol1().obtenerCodigo(Integer.parseInt(codigo.getText()));
       ordenes.setText("Secuencia A Mostrar: "+cadena);
      }
    }//GEN-LAST:event_codigoBActionPerformed

    private void RecPorNivBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecPorNivBActionPerformed
       if(numeros.getArbol1().getRaiz()!=null)
      {
        String cadena = numeros.getArbol1().recorridoPorNivel();
       ordenes.setText("Secuencia A Mostrar: "+cadena);
      }
    }//GEN-LAST:event_RecPorNivBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertaB;
    private javax.swing.JButton RecPorNivB;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton codigoB;
    private javax.swing.JPanel contenedorArbol;
    private javax.swing.JLabel descripcion;
    private javax.swing.JTextField elimina;
    private javax.swing.JButton eliminaB;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondoPrincipal;
    private javax.swing.JButton generaB;
    private javax.swing.JButton inordenB;
    private javax.swing.JTextField inserta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lineaD;
    private javax.swing.JLabel lineaD1;
    private javax.swing.JLabel lineaD10;
    private javax.swing.JLabel lineaD11;
    private javax.swing.JLabel lineaD12;
    private javax.swing.JLabel lineaD13;
    private javax.swing.JLabel lineaD14;
    private javax.swing.JLabel lineaD2;
    private javax.swing.JLabel lineaD3;
    private javax.swing.JLabel lineaD4;
    private javax.swing.JLabel lineaD5;
    private javax.swing.JLabel lineaD6;
    private javax.swing.JLabel lineaD7;
    private javax.swing.JLabel lineaD8;
    private javax.swing.JLabel lineaD9;
    private javax.swing.JLabel lineaI;
    private javax.swing.JLabel lineaI1;
    private javax.swing.JLabel lineaI10;
    private javax.swing.JLabel lineaI11;
    private javax.swing.JLabel lineaI12;
    private javax.swing.JLabel lineaI13;
    private javax.swing.JLabel lineaI14;
    private javax.swing.JLabel lineaI2;
    private javax.swing.JLabel lineaI3;
    private javax.swing.JLabel lineaI4;
    private javax.swing.JLabel lineaI5;
    private javax.swing.JLabel lineaI6;
    private javax.swing.JLabel lineaI7;
    private javax.swing.JLabel lineaI8;
    private javax.swing.JLabel lineaI9;
    private javax.swing.JLabel mostrarOrdenadoTexto;
    private javax.swing.JButton mostrarValNivB;
    private javax.swing.JPanel nivel5;
    private javax.swing.JComboBox<String> nivelCB;
    private javax.swing.JTextField nodo1_1;
    private javax.swing.JTextField nodo2_1;
    private javax.swing.JTextField nodo2_2;
    private javax.swing.JTextField nodo3_1;
    private javax.swing.JTextField nodo3_2;
    private javax.swing.JTextField nodo3_3;
    private javax.swing.JTextField nodo3_4;
    private javax.swing.JTextField nodo4_1;
    private javax.swing.JTextField nodo4_2;
    private javax.swing.JTextField nodo4_3;
    private javax.swing.JTextField nodo4_4;
    private javax.swing.JTextField nodo4_5;
    private javax.swing.JTextField nodo4_6;
    private javax.swing.JTextField nodo4_7;
    private javax.swing.JTextField nodo4_8;
    private javax.swing.JTextField nodo5_1;
    private javax.swing.JTextField nodo5_10;
    private javax.swing.JTextField nodo5_11;
    private javax.swing.JTextField nodo5_12;
    private javax.swing.JTextField nodo5_13;
    private javax.swing.JTextField nodo5_14;
    private javax.swing.JTextField nodo5_15;
    private javax.swing.JTextField nodo5_16;
    private javax.swing.JTextField nodo5_2;
    private javax.swing.JTextField nodo5_3;
    private javax.swing.JTextField nodo5_4;
    private javax.swing.JTextField nodo5_5;
    private javax.swing.JTextField nodo5_6;
    private javax.swing.JTextField nodo5_7;
    private javax.swing.JTextField nodo5_8;
    private javax.swing.JTextField nodo5_9;
    private javax.swing.JComboBox<String> numValoresCB;
    private javax.swing.JLabel numValoresTexto;
    private javax.swing.JLabel ordenes;
    private javax.swing.JButton postordenB;
    private javax.swing.JButton preordenB;
    private javax.swing.JTextField rango;
    private javax.swing.JLabel rangoTexto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
